# Generated by Django 3.0 on 2020-07-21 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingHomeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality1', models.CharField(max_length=150)),
                ('speciality2', models.CharField(max_length=150)),
                ('speciality3', models.CharField(max_length=150)),
                ('reg_no_state', models.CharField(max_length=150)),
                ('reg_no_number', models.CharField(max_length=150)),
                ('reg_no_year', models.CharField(max_length=150)),
                ('picture', models.ImageField(blank=True, upload_to='doctor_document')),
                ('phone_no1', models.CharField(max_length=150)),
                ('email1', models.CharField(max_length=150)),
                ('landline_no', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndivdualUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=150)),
                ('phone_no1', models.CharField(max_length=150)),
                ('email1', models.CharField(max_length=150)),
                ('landline_no', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=150)),
                ('relation_name', models.CharField(max_length=150)),
                ('relation_phone_no', models.CharField(max_length=150)),
                ('relation_email', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndivdualDoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=150)),
                ('speciality1', models.CharField(max_length=150)),
                ('speciality2', models.CharField(max_length=150)),
                ('speciality3', models.CharField(max_length=150)),
                ('practicing_since', models.CharField(max_length=150)),
                ('reg_no_state', models.CharField(max_length=150)),
                ('reg_no_number', models.CharField(max_length=150)),
                ('reg_no_year', models.CharField(max_length=150)),
                ('picture', models.ImageField(blank=True, upload_to='doctor_document')),
                ('phone_no1', models.CharField(max_length=150)),
                ('email1', models.CharField(max_length=150)),
                ('landline_no', models.CharField(max_length=150)),
                ('landline_no1', models.CharField(max_length=150)),
                ('res_house_no', models.CharField(max_length=150)),
                ('res_street', models.CharField(max_length=150)),
                ('res_area', models.CharField(max_length=150)),
                ('res_city', models.CharField(max_length=150)),
                ('res_taluka', models.CharField(max_length=150)),
                ('res_district', models.CharField(max_length=150)),
                ('res_state', models.CharField(max_length=150)),
                ('res_pincode', models.CharField(max_length=150)),
                ('res_country', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality1', models.CharField(max_length=150)),
                ('speciality2', models.CharField(max_length=150)),
                ('speciality3', models.CharField(max_length=150)),
                ('reg_no_state', models.CharField(max_length=150)),
                ('reg_no_number', models.CharField(max_length=150)),
                ('reg_no_year', models.CharField(max_length=150)),
                ('picture', models.ImageField(blank=True, upload_to='doctor_document')),
                ('phone_no1', models.CharField(max_length=150)),
                ('email1', models.CharField(max_length=150)),
                ('landline_no', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
