# Generated by Django 3.0 on 2020-07-21 06:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_onservices', models.CharField(max_length=255)),
                ('add_on_servicescode', models.CharField(max_length=255)),
                ('amount', models.FloatField(default=0)),
                ('cgst', models.FloatField(default=0)),
                ('sgst', models.FloatField(default=0)),
                ('gst', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone_no', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('message', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigationname', models.CharField(max_length=255)),
                ('synonyms', models.CharField(max_length=255)),
                ('importantnotes', models.CharField(max_length=255)),
                ('selectdropdownlist', models.CharField(choices=[('Yes-No', 'Yes-No'), ('Present-Absent', 'Present-Absent'), ('Seen-Not', 'Seen-Not Seen'), ('Positive-Negative', 'Positive-Negative'), ('Customize-Value', 'Customize-Value')], max_length=20)),
                ('select', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(blank=True, max_length=255)),
                ('module_code', models.CharField(blank=True, max_length=255)),
                ('no_of_patients', models.IntegerField(default=0)),
                ('web_space', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('cgst', models.IntegerField(default=0)),
                ('sgst', models.IntegerField(default=0)),
                ('gst', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='pharamcytab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=255)),
                ('addresslineone', models.CharField(max_length=255)),
                ('addresslinetwo', models.CharField(max_length=255)),
                ('streetname', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=266)),
                ('state', models.CharField(max_length=255)),
                ('pincode', models.IntegerField(default=0)),
                ('nationalhead', models.CharField(max_length=266)),
                ('contactnumber', models.CharField(blank=True, max_length=255)),
                ('emailaddress', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(blank=True, max_length=255)),
                ('regionalhead', models.CharField(max_length=255)),
                ('regionalcontactnumber', models.CharField(blank=True, max_length=255)),
                ('regionalemailaddress', models.CharField(max_length=255)),
                ('regionalphonenumber', models.CharField(blank=True, max_length=255)),
                ('scientifichead', models.CharField(max_length=266)),
                ('scientificcontactnumber', models.CharField(blank=True, max_length=255)),
                ('scientificemailaddress', models.EmailField(max_length=254)),
                ('scientificphonenumber', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255)),
                ('answer', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Emptytext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('froms', models.IntegerField()),
                ('to', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=255)),
                ('umo1', models.CharField(blank=True, max_length=255)),
                ('umo2', models.CharField(blank=True, max_length=255)),
                ('conversationfactor', models.CharField(max_length=255)),
                ('refrencerange', models.CharField(choices=[('high', 'high'), ('low', 'low')], max_length=10, verbose_name=models.CharField(blank=True, max_length=255))),
                ('high', models.CharField(choices=[('high', 'high'), ('low', 'low')], max_length=10)),
                ('Labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Emptytext', to='accounts.Labour')),
            ],
            options={
                'verbose_name': 'gender',
                'verbose_name_plural': 'gender',
            },
        ),
        migrations.CreateModel(
            name='Empty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('froms', models.IntegerField()),
                ('to', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('umo1', models.CharField(max_length=255)),
                ('umo2', models.CharField(max_length=255)),
                ('conversationfactor', models.CharField(max_length=255)),
                ('refrencerange', models.CharField(max_length=255)),
                ('high', models.CharField(max_length=244)),
                ('laboratory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Labour')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.CharField(max_length=255, unique=True)),
                ('payment', models.CharField(blank=True, max_length=255, null=True)),
                ('usecode', models.CharField(blank=True, max_length=255, null=True)),
                ('type_of_doctor', models.CharField(blank=True, max_length=255, null=True)),
                ('name_of_hospital', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('taluka', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_doctor_accounts', models.CharField(blank=True, max_length=255, null=True)),
                ('name_of_nursing_home', models.CharField(blank=True, max_length=255, null=True)),
                ('is_individual', models.BooleanField(default=False)),
                ('is_hdc_individual', models.BooleanField(default=False)),
                ('is_hdc_hospital', models.BooleanField(default=False)),
                ('is_hdc_nursing_home', models.BooleanField(default=False)),
                ('special_id', models.CharField(default=None, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
