# Generated by Django 3.0 on 2020-07-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='selectdropdownlist',
            field=models.CharField(choices=[('is_individual', 'is_individual'), ('is_hdc_individual', 'is_hdc_individual'), ('is_hdc_hospital', 'is_hdc_hospital'), ('is_hdc_nursing_home', 'is_hdc_nursing_home')], default='is_individual', max_length=20),
            preserve_default=False,
        ),
    ]
