# Generated by Django 3.0 on 2020-07-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_coupon_selectdropdownlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='selectdropdownlist',
            new_name='Profile_choices',
        ),
        migrations.AddField(
            model_name='coupon',
            name='count_value',
            field=models.IntegerField(default=100),
        ),
    ]
