# Generated by Django 3.0 on 2020-07-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200730_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_from',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='Profile_choices',
            new_name='profileChoices',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_to',
            new_name='startDate',
        ),
    ]
