# Generated by Django 3.0 on 2020-07-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200731_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='startDate',
            field=models.DateField(),
        ),
    ]
